const websitesData = [
    {
        id: 1,
        name: "Creative Portfolio",
        category: "Portfolio",
        description: "A stunning portfolio showcasing creative design work with smooth animations",
        fullDescription: "This beautiful portfolio website features a modern, minimalist design with smooth scroll animations and interactive elements. Perfect for designers, photographers, and creative professionals looking to showcase their work in an elegant way.",
        image: "superman1.jpg",
        url: "https://kristiantorres1.github.io/Portfolio-/portfolio.html",
        tags: ["Design", "Creative", "Portfolio"],
        features: ["Responsive Design", "Smooth Animations", "Dark Mode", "Image Gallery"],
        technologies: ["HTML5", "CSS3", "JavaScript", "GSAP"]
    },
    {
    id: 2,
    name: "Fast Food Restaurant",
    category: "Restaurant",
    description: "Modern fast-casual eatery with fresh ingredients, customizable bowls, and fast checkout.",
    fullDescription: "A fully-featured e-commerce platform built with user experience in mind. Includes product browsing, cart management, secure checkout, and user account features. The design is clean and intuitive, making shopping a breeze.",
    image: "websitt.jpg",
    urll: "https://themewagon.github.io/feane/index.html",
     url: "https://themewagon.com/themes/free-bootstrap-4-html5-restaurant-website-template-feane/",  // ✅ Add your download link here
    tags: ["Shopping", "Business", "E-Commerce"],
    features: ["Product Catalog", "Shopping Cart", "Secure Payments", "User Accounts"],
    technologies: ["React", "Node.js", "Stripe API", "MongoDB"]
},
    {
        id: 3,
        name: "Tech Startup Landing",
        category: "Landing Page",
        description: "Eye-catching landing page for a tech startup with modern aesthetics",
        fullDescription: "A high-converting landing page designed for tech startups. Features compelling hero sections, feature highlights, testimonials, and clear call-to-action buttons. Built to capture attention and drive conversions.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
        url: "https://www.producthunt.com",
        tags: ["Startup", "Landing Page", "Marketing"],
        features: ["Hero Section", "Feature Showcase", "Testimonials", "CTA Buttons"],
        technologies: ["HTML5", "TailwindCSS", "JavaScript", "AOS"]
    },
    {
        id: 4,
        name: "Blog & Magazine",
        category: "Blog",
        description: "Content-rich blog with elegant typography and reading experience",
        fullDescription: "A beautifully designed blog and magazine platform that puts content first. Features excellent typography, readable layouts, category organization, and social sharing capabilities. Perfect for writers and publishers.",
        image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=600&fit=crop",
        url: "https://medium.com",
        tags: ["Content", "Blog", "Publishing"],
        features: ["Article Management", "Categories", "Social Sharing", "Comments"],
        technologies: ["WordPress", "PHP", "MySQL", "JavaScript"]
    },
    {
        id: 5,
        name: "Restaurant Website",
        category: "Restaurant",
        description: "Delicious restaurant website with menu showcase and online ordering",
        fullDescription: "An appetizing restaurant website featuring mouth-watering imagery, detailed menu presentations, online reservation system, and delivery options. The design creates a warm, inviting atmosphere that reflects the dining experience.",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
        url: "https://www.opentable.com",
        tags: ["Food", "Restaurant", "Local Business"],
        features: ["Menu Display", "Online Reservations", "Gallery", "Contact Form"],
        technologies: ["HTML5", "CSS3", "JavaScript", "Google Maps API"]
    },
    {
        id: 6,
        name: "Fitness & Wellness",
        category: "Health",
        description: "Dynamic fitness website with workout plans and progress tracking",
        fullDescription: "A comprehensive fitness and wellness platform offering workout programs, nutrition guides, progress tracking, and community features. The energetic design motivates users to achieve their health goals.",
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop",
        url: "https://www.myfitnesspal.com",
        tags: ["Fitness", "Health", "Lifestyle"],
        features: ["Workout Plans", "Progress Tracking", "Nutrition Guides", "Community"],
        technologies: ["Vue.js", "Firebase", "Chart.js", "REST API"]
    },
    {
        id: 7,
        name: "Travel Adventure",
        category: "Travel",
        description: "Inspiring travel website with destination guides and booking features",
        fullDescription: "An inspiring travel platform that helps users discover new destinations, plan trips, and book accommodations. Features stunning photography, detailed destination guides, and seamless booking integration.",
        image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
        url: "https://www.airbnb.com",
        tags: ["Travel", "Tourism", "Adventure"],
        features: ["Destination Guides", "Booking System", "Reviews", "Interactive Maps"],
        technologies: ["React", "Node.js", "Mapbox", "Payment Gateway"]
    },
    {
        id: 8,
        name: "Photography Studio",
        category: "Portfolio",
        description: "Elegant photography portfolio with fullscreen galleries",
        fullDescription: "A stunning photography portfolio showcasing professional work through fullscreen galleries, slideshow presentations, and client testimonials. The minimalist design ensures photos take center stage.",
        image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=600&fit=crop",
        url: "https://unsplash.com",
        tags: ["Photography", "Art", "Portfolio"],
        features: ["Fullscreen Galleries", "Slideshows", "Client Area", "Print Shop"],
        technologies: ["HTML5", "CSS Grid", "Lightbox.js", "Lazy Loading"]
    },
    {
        id: 9,
        name: "SaaS Dashboard",
        category: "SaaS",
        description: "Professional SaaS application with analytics and data visualization",
        fullDescription: "A sophisticated SaaS dashboard offering comprehensive analytics, data visualization, user management, and reporting tools. The interface is clean and intuitive, making complex data easy to understand.",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
        url: "https://www.tableau.com",
        tags: ["SaaS", "Analytics", "Business"],
        features: ["Analytics Dashboard", "Data Visualization", "Reports", "Team Management"],
        technologies: ["Angular", "D3.js", "TypeScript", "REST API"]
    },
    {
        id: 10,
        name: "Education Platform",
        category: "Education",
        description: "Interactive learning platform with courses and progress tracking",
        fullDescription: "A comprehensive online learning platform featuring video courses, interactive quizzes, progress tracking, and certification programs. Designed to make education accessible and engaging for all learners.",
        image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop",
        url: "https://www.coursera.org",
        tags: ["Education", "E-Learning", "Courses"],
        features: ["Video Courses", "Quizzes", "Certificates", "Discussion Forums"],
        technologies: ["React", "Video.js", "MongoDB", "Express"]
    },
    {
        id: 11,
        name: "Real Estate Listings",
        category: "Real Estate",
        description: "Property listing website with advanced search and virtual tours",
        fullDescription: "A modern real estate platform featuring property listings, advanced search filters, virtual tours, and mortgage calculators. The design is professional and trustworthy, helping buyers find their dream homes.",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
        url: "https://www.zillow.com",
        tags: ["Real Estate", "Property", "Business"],
        features: ["Property Listings", "Search Filters", "Virtual Tours", "Mortgage Calculator"],
        technologies: ["React", "Google Maps API", "3D Tours", "PostgreSQL"]
    },
    {
        id: 12,
        name: "Learning sites",
        category: "Entertainment",
        description: "Sleek music streaming platform with playlists and discovery features",
        fullDescription: "A beautiful music streaming platform offering personalized playlists, music discovery, social features, and high-quality audio. The interface is intuitive and makes finding your favorite music effortless.",
        image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop",
        url: "https://www.spotify.com",
        tags: ["Music", "Entertainment", "Streaming"],
        features: ["Music Player", "Playlists", "Discovery", "Social Features"],
        technologies: ["React", "Web Audio API", "Node.js", "WebSockets"]
    },
    {
        id: 13,
        name: "Capstone archive",
        category: "Entertainment",
        description: "Sleek music streaming platform with playlists and discovery features",
        fullDescription: "A beautiful music streaming platform offering personalized playlists, music discovery, social features, and high-quality audio. The interface is intuitive and makes finding your favorite music effortless.",
        image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop",
        url: "https://www.spotify.com",
        tags: ["Music", "Entertainment", "Streaming"],
        features: ["Music Player", "Playlists", "Discovery", "Social Features"],
        technologies: ["React", "Web Audio API", "Node.js", "WebSockets"]
    }
];                                                                 